system:
  signalConfigurationParameter:
    heartbeatInterval: 60
    maxRetransmit: 3
    ackTimeout: 30
    ackRandomFactor: 8888
  secureFile:
    serverCertFile: ../certs/server-cert.pem
    serverKeyFile: ../certs/server-key.pem
    crlFile: ../certs/crl.pem
    certFile: ../certs/ca-cert.pem
  network:
    bindAddress: "::"
    signalChannelPort: 4646
    dataChannelPort: 4647
  database:
    name: dots
    username: root
    password: dotsroot
    protocol: tcp
    host: 172.16.236.12
    port: 3306
    databaseName: dots
  aaa:
    enable: true
    host: 172.16.236.18
    port: 1812
    secret: testing123
    serviceType: Administrative
