version: "2.1"

services:
    freediameter:
        container_name: freediameter
        build: .
        privileged: true
        environment:
          - TZ=Asia/Tokyo
        ports:
          - 3868:3868
          - 5658:5658
        hostname: diameter
        domainname: example.com
        depends_on:
          - diameap_db
        volumes:
          - ../certs/ca-cert.pem:/etc/ssl/certs/ca-cert.pem:ro
          - ../certs/ca-key.pem:/etc/ssl/certs/ca-key.pem:ro
          - ../certs/server-cert.pem:/etc/ssl/certs/server-cert.pem:ro
          - ../certs/server-key.pem:/etc/ssl/certs/server-key.pem:ro
          - ../certs/aaa-cert.pem:/etc/ssl/certs/freeDiameter.pem:ro
          - ../certs/aaa-key.pem:/etc/ssl/private/freeDiameter.key:ro
          - ./config:/config:ro
          - ../certs:/certs:ro
    diameap_db:
        container_name: diameap_db
        image: mysql:5.7
        restart: always
        environment:
            - TZ=Asia/Tokyo
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=diamEAP
            - MYSQL_USER=diamEAP
            - MYSQL_PASSWORD=diamEAP
        ports:
            - 13306:3306
        volumes:
            - ./init_db/diameap.sql:/docker-entrypoint-initdb.d/1.diameap.sql
