version: "2.1"

services:
  freediameter:
    container_name: freediameter
    build: .
    privileged: true
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3868:3868
      - 5658:5658
    hostname: diameter
    domainname: example.com
    networks:
      - aaa
    depends_on:
      - diameap_db
    volumes:
      - ./config:/config:ro
      - ../certs:/certs:ro
    extra_hosts:
      - "client.example.com:172.23.0.254"
  diameap_db:
    container_name: diameap_db
    image: mysql:5.7
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=diamEAP
      - MYSQL_USER=diamEAP
      - MYSQL_PASSWORD=diamEAP
    ports:
      - 13306:3306
    networks:
      - aaa
    volumes:
      - ./init_db/diameap.sql:/docker-entrypoint-initdb.d/1.diameap.sql
      - ./init_db/diam_user.sql:/docker-entrypoint-initdb.d/2.diam_user.sql
networks:
  aaa:
    ipam:
      config:
        - subnet: 172.23.0.0/24
          ip_range: 172.23.0.0/24
          gateway: 172.23.0.254
