version: "2.1"

services:
    gobgp:
        container_name: gobgp-standalone
        build: .
        privileged: true
        ports:
          - "50051:50051"
        stdin_open: true
        tty: true